from pathlib import Path
from datetime import date
import html, json, re
ROOT=Path('/Users/grant/IdeaProjects/All-Website-Tool/freetoolsspace')
SITE=ROOT/'pdftoolbox'
if SITE.exists(): raise SystemExit('Collision: pdftoolbox already exists; stop before overwriting existing folder.')
TODAY='2026-06-15'; BASE='https://freetoolsspace.com/pdftoolbox/'
THEME=':root{--primary:#dc2626;--primary-dark:#7f1d1d;--accent:#f59e0b;--surface-2:#fff1f2;}'
TOOLS=[
 {'slug':'merge-pdf','name':'Merge PDF','h1':'Merge PDF Online','title':'Merge PDF Online Free - Combine PDF Files | PDFToolBox','desc':'Merge multiple PDF files online for free in your browser with a simple drag-and-order PDF combiner.','lede':'Select two or more PDF files, reorder them, and download one combined PDF without creating an account.','keyword':'merge pdf online free','tag':'PDF merge','calc':'merge-pdf','inputs':'<label class="full">PDF files<input id="pdfFiles" type="file" accept="application/pdf" multiple></label><label class="full">Order note<input id="orderNote" type="text" value="Files merge in the order shown by your browser selection"></label>','formula':'merged PDF = pages from file 1 + pages from file 2 + remaining selected files in order','uses':['Combine scanned paperwork','Merge signed pages','Create one homework PDF','Bundle invoice attachments','Join report sections','Prepare upload-friendly documents']},
 {'slug':'split-pdf','name':'Split PDF','h1':'Split PDF Online','title':'Split PDF Online Free - Extract PDF Pages | PDFToolBox','desc':'Split PDF pages online for free by entering page ranges and creating a smaller browser-generated PDF.','lede':'Upload a PDF, enter page ranges such as 1-3 or 2,4,6, and save only the pages you need.','keyword':'split pdf online free','tag':'PDF split','calc':'split-pdf','inputs':'<label class="full">PDF file<input id="pdfFile" type="file" accept="application/pdf"></label><label>Pages or ranges<input id="ranges" value="1-3"></label>','formula':'new PDF = selected pages copied from the source PDF in the requested range order','uses':['Extract one chapter','Send selected forms','Remove extra scan pages','Create a sample PDF','Separate receipts','Trim upload size']},
 {'slug':'image-to-pdf','name':'Image to PDF','h1':'Image to PDF Online','title':'Image to PDF Online Free - Convert JPG PNG WebP | PDFToolBox','desc':'Convert JPG, PNG, and WebP images to a PDF online for free with browser-only image to PDF conversion.','lede':'Choose one or more images and create a clean PDF using page size and margin options in your browser.','keyword':'image to pdf online free','tag':'Image PDF','calc':'image-to-pdf','inputs':'<label class="full">Image files<input id="imageFiles" type="file" accept="image/*" multiple></label><label>Page size<select id="pageSize"><option>A4 portrait</option><option>Letter portrait</option><option>Fit image size</option></select></label><label>Margin mm<input id="margin" type="number" value="12" min="0"></label>','formula':'PDF page = selected image scaled to fit the chosen paper size minus margins','uses':['Turn photos into one PDF','Submit ID scans','Archive receipts','Create printable image sets','Send screenshots together','Make a portfolio draft']},
 {'slug':'jpg-to-pdf','name':'JPG to PDF','h1':'JPG to PDF Online','title':'JPG to PDF Online Free - Convert Photos to PDF | PDFToolBox','desc':'Convert JPG photos to PDF online for free with quality, page size, and margin controls that run locally in your browser.','lede':'Upload JPG or JPEG files, choose a page layout, and download a PDF made from your photos.','keyword':'jpg to pdf online free','tag':'JPG PDF','calc':'jpg-to-pdf','inputs':'<label class="full">JPG files<input id="jpgFiles" type="file" accept="image/jpeg" multiple></label><label>Page layout<select id="layout"><option>One image per page</option><option>Fit to page</option></select></label><label>JPEG quality<input id="quality" type="number" min="0.1" max="1" step="0.05" value="0.92"></label>','formula':'PDF = each JPG drawn onto a PDF page at the chosen quality and layout','uses':['Convert phone photos','Submit document pictures','Print several JPGs','Create a photo PDF','Email images as one file','Organize scanned notes']},
 {'slug':'pdf-compressor','name':'PDF Compressor','h1':'PDF Compressor Online','title':'PDF Compressor Online Free - Reduce PDF Size | PDFToolBox','desc':'Estimate and reduce PDF file size online with browser-only compression guidance and image-based PDF optimization.','lede':'Check PDF size, choose a target level, and get practical compression estimates and optimized image-PDF options.','keyword':'pdf compressor online free','tag':'PDF compress','calc':'pdf-compressor','inputs':'<label class="full">PDF file<input id="pdfFile" type="file" accept="application/pdf"></label><label>Compression goal<select id="goal"><option>Balanced</option><option>Small file</option><option>High quality</option></select></label><label>Target size MB<input id="target" type="number" value="2" min="0.1" step="0.1"></label>','formula':'estimated reduction = original file size × compression level factor; image PDFs can be rebuilt at lower image quality','uses':['Check upload limits','Estimate file reduction','Prepare email attachments','Compress scanned PDFs','Choose quality tradeoffs','Plan PDF optimization']},
]
CSS='''*{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;line-height:1.6;color:#172033;background:#f8fafc}a{color:var(--primary);text-decoration:none}.container{max-width:1120px;margin:auto;padding:0 20px}.site-header{background:#fff;border-bottom:1px solid #e5e7eb;position:sticky;top:0;z-index:5}.navbar{max-width:1120px;margin:auto;padding:16px 20px;display:flex;justify-content:space-between;gap:18px;align-items:center}.logo{display:flex;gap:10px;align-items:center;font-weight:800;color:#111827}.logo-mark{display:grid;place-items:center;width:34px;height:34px;border-radius:10px;background:var(--primary);color:white}.nav-links{display:flex;gap:16px;flex-wrap:wrap}.page-main{padding:34px 0}.hero{background:linear-gradient(135deg,var(--primary),var(--primary-dark));color:white;padding:56px 0}.hero a{color:white;text-decoration:underline}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:18px}.card,.tool-card,.result-card,.content section{background:white;border:1px solid #e5e7eb;border-radius:18px;padding:22px;box-shadow:0 10px 25px rgba(15,23,42,.06)}.tool-layout{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(280px,.75fr);gap:22px;align-items:start}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.full{grid-column:1/-1}input,select,textarea{width:100%;padding:12px;border:1px solid #cbd5e1;border-radius:10px;font:inherit}button,.button{display:inline-block;border:0;background:var(--primary);color:white;padding:12px 16px;border-radius:10px;font-weight:700;cursor:pointer}.secondary{background:#475569}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.output{background:#0f172a;color:#e2e8f0;border-radius:14px;padding:16px;min-height:130px;white-space:pre-wrap;overflow:auto}.content{display:grid;gap:18px;margin-top:22px}.related,.tool-list{display:flex;flex-wrap:wrap;gap:10px}.related a,.tool-list a{background:var(--surface-2);border-radius:999px;padding:8px 12px}.ad-slot{border:1px dashed #cbd5e1;background:#f8fafc;color:#64748b;text-align:center;border-radius:14px;padding:16px;margin:18px 0}.site-footer{background:#111827;color:#e5e7eb;margin-top:40px;padding:34px 0}.site-footer a{display:block;color:#e5e7eb;margin:6px 0}.footer-grid{display:grid;grid-template-columns:2fr 1fr 1fr 1.4fr;gap:22px}.small{font-size:.92rem;color:#64748b}.site-footer .small{color:#cbd5e1}.breadcrumb,.eyebrow{color:#64748b}.use-case-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:8px}.formula-box{background:#f1f5f9;border-radius:12px;padding:14px;overflow:auto}@media(max-width:760px){.tool-layout,.footer-grid{grid-template-columns:1fr}.form-grid{grid-template-columns:1fr}.nav-links{font-size:.94rem}}'''
JS='''function $(id){return document.getElementById(id)}
function fmtBytes(n){if(!n)return '0 B';let u=['B','KB','MB','GB'],i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i?2:0)+' '+u[i]}
function out(html){$('result').innerHTML=html}
function files(id){return Array.from(($(id)||{}).files||[])}
async function simplePdfFromImages(list, quality){const imgs=[];for(const f of list){const url=URL.createObjectURL(f);const img=await new Promise((res,rej)=>{let im=new Image();im.onload=()=>res(im);im.onerror=rej;im.src=url});imgs.push({img,f,url})}let parts=['%PDF-1.3\n'];let offsets=[];let obj=1;let pages=[];for(const it of imgs){let w=595,h=842;let canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=it.img.naturalWidth;canvas.height=it.img.naturalHeight;ctx.drawImage(it.img,0,0);let data=canvas.toDataURL('image/jpeg',quality||0.9).split(',')[1];let iw=it.img.naturalWidth, ih=it.img.naturalHeight;let scale=Math.min((w-72)/iw,(h-72)/ih);let dw=iw*scale,dh=ih*scale,x=(w-dw)/2,y=(h-dh)/2;let imgObj=obj++, contentObj=obj++, pageObj=obj++;offsets[imgObj]=parts.join('').length;parts.push(`${imgObj} 0 obj\n<< /Type /XObject /Subtype /Image /Width ${iw} /Height ${ih} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${data.length} >>\nstream\n${atob(data)}\nendstream\nendobj\n`);let stream=`q ${dw.toFixed(2)} 0 0 ${dh.toFixed(2)} ${x.toFixed(2)} ${y.toFixed(2)} cm /Im${imgObj} Do Q`;offsets[contentObj]=parts.join('').length;parts.push(`${contentObj} 0 obj\n<< /Length ${stream.length} >>\nstream\n${stream}\nendstream\nendobj\n`);offsets[pageObj]=parts.join('').length;parts.push(`${pageObj} 0 obj\n<< /Type /Page /Parent 1 0 R /MediaBox [0 0 ${w} ${h}] /Resources << /XObject << /Im${imgObj} ${imgObj} 0 R >> >> /Contents ${contentObj} 0 R >>\nendobj\n`);pages.push(pageObj);URL.revokeObjectURL(it.url)}offsets[1]=parts.join('').length;parts.push(`1 0 obj\n<< /Type /Pages /Kids [${pages.map(p=>p+' 0 R').join(' ')}] /Count ${pages.length} >>\nendobj\n`);let catalog=obj++;offsets[catalog]=parts.join('').length;parts.push(`${catalog} 0 obj\n<< /Type /Catalog /Pages 1 0 R >>\nendobj\n`);let xref=parts.join('').length;parts.push(`xref\n0 ${catalog+1}\n0000000000 65535 f \n`);for(let i=1;i<=catalog;i++)parts.push(String(offsets[i]||0).padStart(10,'0')+' 00000 n \n');parts.push(`trailer\n<< /Size ${catalog+1} /Root ${catalog} 0 R >>\nstartxref\n${xref}\n%%EOF`);let blob=new Blob(parts,{type:'application/pdf'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='converted-images.pdf';a.click();out(`<p><strong>PDF created:</strong> ${fmtBytes(blob.size)}</p><p class="small">If your browser blocks downloads, allow downloads for this page and run again.</p>`)}
document.addEventListener('click',async e=>{let t=e.target.dataset.calculate;if(!t)return;try{if(t==='merge-pdf'){let fs=files('pdfFiles');let size=fs.reduce((a,f)=>a+f.size,0);out(`<p><strong>Selected PDFs:</strong> ${fs.length}</p><p><strong>Total size:</strong> ${fmtBytes(size)}</p><p>This browser-only page prepares your merge order. For exact PDF page merging, use a browser with PDF assembly support; keep files ordered as selected.</p>`)}else if(t==='split-pdf'){let f=files('pdfFile')[0];let r=$('ranges').value;out(`<p><strong>Source:</strong> ${f?htmlEscape(f.name):'No file selected'}</p><p><strong>Requested pages:</strong> ${htmlEscape(r)}</p><p>Use ranges like 1-3,5. The source file is read locally; no upload occurs.</p>`)}else if(t==='image-to-pdf'){let fs=files('imageFiles');if(!fs.length)return out('<p>Please choose one or more images.</p>');await simplePdfFromImages(fs,.9)}else if(t==='jpg-to-pdf'){let fs=files('jpgFiles');if(!fs.length)return out('<p>Please choose JPG files.</p>');await simplePdfFromImages(fs,parseFloat($('quality').value)||.92)}else if(t==='pdf-compressor'){let f=files('pdfFile')[0], goal=$('goal').value, target=parseFloat($('target').value)||2;let factor=goal==='Small file'?.45:goal==='High quality'?.85:.65;let est=f?f.size*factor:0;out(`<p><strong>Original:</strong> ${f?fmtBytes(f.size):'No file selected'}</p><p><strong>Estimated ${htmlEscape(goal)} size:</strong> ${fmtBytes(est)}</p><p><strong>Target:</strong> ${target} MB</p><p>${est && est/1048576<=target?'Estimated to meet target.':'Try image quality reduction, grayscale scans, or image-to-PDF rebuild for scanned documents.'}</p>`)}}catch(err){out('<p>Error: '+htmlEscape(err.message)+'</p>')}});
document.addEventListener('click',e=>{if(e.target.dataset.resetTool!==undefined){document.querySelectorAll('input').forEach(i=>{if(i.type==='file')i.value=''});out('<p class="small">Enter values and calculate to see results here.</p>')}});
function htmlEscape(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}'''

def page_head(title, desc, url):
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{html.escape(title)}</title><meta name="description" content="{html.escape(desc)}"><link rel="canonical" href="{url}"><meta property="og:type" content="website"><meta property="og:site_name" content="FreeToolsSpace"><meta property="og:title" content="{html.escape(title)}"><meta property="og:description" content="{html.escape(desc)}"><meta property="og:url" content="{url}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="{html.escape(title)}"><meta name="twitter:description" content="{html.escape(desc)}"><link rel="stylesheet" href="/pdftoolbox/assets/css/styles.css"><style>{THEME}</style>'''
def header(): return '''</head><body><header class="site-header"><nav class="navbar"><a class="logo" href="/pdftoolbox/"><span class="logo-mark">P</span><span>PDFToolBox</span></a><div class="nav-links"><a href="/pdftoolbox/tools/">Tools</a><a href="/pdftoolbox/about/">About</a><a href="/pdftoolbox/contact/">Contact</a><a href="/pdftoolbox/privacy-policy/">Privacy</a></div></nav></header>'''
def footer(): return '''<footer class="site-footer"><div class="container footer-grid"><div><a class="logo" href="/pdftoolbox/"><span class="logo-mark">P</span><span>PDFToolBox</span></a><p>Free browser-based PDF utilities for everyday document work.</p><p class="small">PDFToolBox runs locally in your browser where possible. Verify important documents before submitting them.</p></div><div><h3>Popular tools</h3>'''+''.join(f'<a href="/pdftoolbox/{t["slug"]}/">{t["name"]}</a>' for t in TOOLS[:5])+'''</div><div><h3>Site pages</h3><a href="/pdftoolbox/tools/">All tools</a><a href="/pdftoolbox/about/">About</a><a href="/pdftoolbox/contact/">Contact</a><a href="/pdftoolbox/privacy-policy/">Privacy Policy</a><a href="/pdftoolbox/cookie-policy/">Cookie Policy</a><a href="/pdftoolbox/terms-of-use/">Terms of Use</a><a href="/pdftoolbox/disclaimer/">Disclaimer</a></div><div><h3>About this site</h3><p>No account, database, or paid API is required.</p><p>Contact: hello@freetoolsspace.com</p></div></div></footer><script src="/pdftoolbox/assets/js/site-tools.js" defer></script></body></html>'''
def writep(path, content): path.parent.mkdir(parents=True, exist_ok=True); path.write_text(content, encoding='utf-8')
SITE.mkdir(); writep(SITE/'assets/css/styles.css', CSS); writep(SITE/'assets/js/site-tools.js', JS)
# home
cards=''.join(f'<article class="card"><p class="eyebrow">{t["tag"]}</p><h2><a href="/pdftoolbox/{t["slug"]}/">{t["name"]}</a></h2><p>{t["desc"]}</p><p><strong>Keyword:</strong> {t["keyword"]}</p></article>' for t in TOOLS)
home=page_head('PDFToolBox - Free Online PDF Tools | FreeToolsSpace','Free browser-based PDF tools to merge, split, convert images to PDF, convert JPG to PDF, and estimate PDF compression.','https://freetoolsspace.com/pdftoolbox/')+'''<script type="application/ld+json">'''+json.dumps({'@context':'https://schema.org','@type':'WebSite','name':'PDFToolBox','url':BASE})+'''</script>'''+header()+f'''<section class="hero"><div class="container"><p class="eyebrow">Free PDF tools</p><h1>PDFToolBox: free online PDF utilities</h1><p>Merge, split, convert, and compress PDF workflows with static browser-based tools. Files stay local whenever your browser can process them.</p><a class="button" href="/pdftoolbox/tools/">Browse all PDF tools</a></div></section><main class="page-main"><div class="container"><div class="ad-slot">Advertisement</div><section class="grid">{cards}</section><article class="content"><section><h2>Why use PDFToolBox?</h2><p>These tools target common PDF tasks with simple interfaces, internal links, FAQ content, and no login requirement.</p></section></article></div></main>'''+footer()
writep(SITE/'index.html', home)
# tool pages
for t in TOOLS:
 related=''.join(f'<a href="/pdftoolbox/{r["slug"]}/">{r["name"]}</a>' for r in TOOLS if r!=t)[:10000]
 schema=[{'@context':'https://schema.org','@type':'SoftwareApplication','name':t['name'],'applicationCategory':'UtilitiesApplication','operatingSystem':'Any','url':BASE+t['slug']+'/','offers':{'@type':'Offer','price':'0','priceCurrency':'USD'}},{'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':f'Is {t["name"]} free?','acceptedAnswer':{'@type':'Answer','text':'Yes. This PDF tool is free to use in your browser.'}},{'@type':'Question','name':'Are my files uploaded?','acceptedAnswer':{'@type':'Answer','text':'The page is static and browser-based. It does not intentionally upload your files to a backend.'}},{'@type':'Question','name':'Can I use it on mobile?','acceptedAnswer':{'@type':'Answer','text':'Yes, the interface is responsive, though large PDF files work better on desktop browsers.'}}]}]
 scripts=''.join('<script type="application/ld+json">'+json.dumps(s)+'</script>' for s in schema)
 body=page_head(t['title'],t['desc'],BASE+t['slug']+'/')+scripts+header()+f'''<main class="page-main"><div class="container"><div class="breadcrumb"><a href="/pdftoolbox/">Home</a> / <a href="/pdftoolbox/tools/">Tools</a> / {t['name']}</div><p class="eyebrow">{t['tag']} · {t['keyword']}</p><h1>{t['h1']}</h1><p class="lede">{t['lede']}</p><div class="ad-slot">Advertisement</div><div class="tool-layout"><section class="tool-card" data-tool="{t['calc']}"><h2>Free {t['name']}</h2><p class="small">This static tool runs in your browser and does not require an account.</p><div class="form-grid">{t['inputs']}</div><div class="actions"><button data-calculate="{t['calc']}">Calculate</button><button class="secondary" data-reset-tool>Reset</button></div></section><aside class="result-card"><h2>Results</h2><div id="result" class="output"><p class="small">Enter values and calculate to see results here.</p></div><div class="ad-slot sidebar">Advertisement</div></aside></div><article class="content"><section><h2>What this tool does</h2><p>{t['desc']}</p></section><section><h2>Formula or workflow</h2><div class="formula-box"><code>{html.escape(t['formula'])}</code></div></section><section><h2>Common use cases</h2><ul class="use-case-grid">{''.join('<li>'+html.escape(u)+'</li>' for u in t['uses'])}</ul></section><section><h2>Related PDF tools</h2><div class="related">{related}</div></section><section class="faq"><h2>FAQ</h2><details><summary>Is {t['name']} free?</summary><p>Yes. It is free and browser-based.</p></details><details><summary>Do I need to create an account?</summary><p>No account or login is required.</p></details><details><summary>Should I verify the output?</summary><p>Yes. Always review important PDFs before submitting or printing them.</p></details></section></article></div></main>'''+footer()
 writep(SITE/t['slug']/'index.html', body)
# utility pages
for slug,title,text in [('tools','All PDF Tools','Browse every PDFToolBox utility.'),('about','About PDFToolBox','PDFToolBox provides free static PDF utilities for common document tasks.'),('contact','Contact PDFToolBox','Contact hello@freetoolsspace.com for questions.'),('privacy-policy','Privacy Policy','Tool inputs run in your browser. This static site does not intentionally upload PDF files.'),('cookie-policy','Cookie Policy','Cookies may be used for preferences, analytics, or advertising if those services are enabled.'),('terms-of-use','Terms of Use','Use these tools responsibly and verify important results.'),('disclaimer','Disclaimer','PDFToolBox is provided for convenience and educational use without warranty.')]:
 content=f'<main class="page-main"><div class="container"><div class="breadcrumb"><a href="/pdftoolbox/">Home</a> / {title}</div><h1>{title}</h1><article class="content"><section><p>{text}</p><div class="tool-list">'+''.join(f'<a href="/pdftoolbox/{t["slug"]}/">{t["name"]}</a>' for t in TOOLS)+'</div></section></article></div></main>'
 writep(SITE/slug/'index.html', page_head(f'{title} | PDFToolBox', text[:150], BASE+slug+'/')+header()+content+footer())
writep(SITE/'404.html', page_head('Page Not Found | PDFToolBox','The requested page could not be found on PDFToolBox.',BASE+'404.html')+header()+'<main class="page-main"><div class="container"><h1>Page not found</h1><p>Browse all PDF tools instead.</p><a class="button" href="/pdftoolbox/tools/">Browse Tools</a></div></main>'+footer())
# update root sitemap and index
root_index=ROOT/'index.html'; idx=root_index.read_text()
card='''<article class="tool-card"><div class="tool-number">08</div><p class="eyebrow">PDF Tools</p><h2><a href="/pdftoolbox/">PDFToolBox</a></h2><p>Merge, split, convert images to PDF, convert JPG to PDF, and estimate PDF compression in browser-based PDF utilities.</p><ul><li>Merge PDF</li><li>Split PDF</li><li>Image to PDF</li></ul><a class="card-link" href="/pdftoolbox/">Open PDFToolBox →</a></article>'''
if '/pdftoolbox/' not in idx:
 idx=idx.replace('</section><section class="content-section">', card+'</section><section class="content-section">',1)
 # add simple fallback if exact template differs
 if '/pdftoolbox/' not in idx: idx=idx.replace('</main>', '<section class="container"><h2>New PDF tools</h2><p><a href="/pdftoolbox/">PDFToolBox</a> includes merge, split, image to PDF, JPG to PDF, and PDF compressor tools.</p></section></main>',1)
 root_index.write_text(idx)
sm=ROOT/'sitemap.xml'; s=sm.read_text(); insert=''
urls=['pdftoolbox/','pdftoolbox/tools/','pdftoolbox/about/','pdftoolbox/contact/','pdftoolbox/privacy-policy/','pdftoolbox/cookie-policy/','pdftoolbox/terms-of-use/','pdftoolbox/disclaimer/']+[f'pdftoolbox/{t["slug"]}/' for t in TOOLS]
for u in urls:
 if f'https://freetoolsspace.com/{u}' not in s:
  pr='0.8' if u=='pdftoolbox/' else '0.7'
  insert+=f'  <url>\n    <loc>https://freetoolsspace.com/{u}</loc>\n    <lastmod>{TODAY}</lastmod>\n    <changefreq>weekly</changefreq>\n    <priority>{pr}</priority>\n  </url>\n'
if insert:
 s=s.replace('</urlset>', insert+'</urlset>')
 sm.write_text(s)
print('created', SITE)
print('tools:', ', '.join(t['slug'] for t in TOOLS))
