#!/usr/bin/env python3
from pathlib import Path
from datetime import date
import html, json, re
ROOT = Path('/Users/grant/IdeaProjects/All-Website-Tool/freetoolsspace')
SITE = ROOT / 'imagetoolbox'
if SITE.exists():
    raise SystemExit('Collision: imagetoolbox already exists; stop before overwriting existing folder.')
TODAY='2026-06-15'
BASE='https://freetoolsspace.com/imagetoolbox/'
THEME=':root{--primary:#db2777;--primary-dark:#831843;--accent:#06b6d4;--surface-2:#fdf2f8;}'
TOOLS=[
 {'slug':'image-compressor','name':'Image Compressor','h1':'Image Compressor Online','title':'Image Compressor Online - Compress JPG, PNG and WebP | ImageToolBox','desc':'Compress JPG, PNG, and WebP images in your browser with a free online image compressor and quality slider.','lede':'Choose an image, adjust quality and max width, then export a smaller JPEG or WebP file locally in your browser.','keyword':'image compressor online','tag':'Compression','calc':'image-compressor','inputs':'<label class="full">Image file<input id="imageFile" type="file" accept="image/*"></label><label>Output format<select id="format"><option value="image/jpeg">JPEG</option><option value="image/webp">WebP</option><option value="image/png">PNG</option></select></label><label>Quality 0.1-1<input id="quality" type="number" min="0.1" max="1" step="0.05" value="0.8"></label><label>Max width px (optional)<input id="maxWidth" type="number" min="1" value="1600"></label>','formula':'new image size depends on canvas dimensions, output format, and compression quality','uses':['Compress blog images','Reduce upload file size','Create email-friendly images','Prepare faster web graphics','Compare JPEG and WebP output','Resize oversized screenshots']},
 {'slug':'image-resizer','name':'Image Resizer','h1':'Image Resizer Online','title':'Image Resizer Online - Resize Images by Pixels | ImageToolBox','desc':'Resize images by width and height in your browser with a free online image resizer for JPG, PNG, and WebP files.','lede':'Upload an image, set pixel dimensions, choose fit mode, and download a resized copy without sending the file anywhere.','keyword':'resize image online','tag':'Resize','calc':'image-resizer','inputs':'<label class="full">Image file<input id="imageFile" type="file" accept="image/*"></label><label>Width px<input id="width" type="number" min="1" value="1200"></label><label>Height px<input id="height" type="number" min="1" value="800"></label><label>Mode<select id="mode"><option value="contain">Fit inside size</option><option value="stretch">Stretch to exact size</option></select></label><label>Output format<select id="format"><option value="image/jpeg">JPEG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select></label>','formula':'resized pixels = target width × target height, with optional aspect-ratio preservation','uses':['Resize profile pictures','Scale product photos','Prepare article images','Make thumbnails','Fit social post sizes','Shrink large camera photos']},
 {'slug':'png-to-jpg-converter','name':'PNG to JPG Converter','h1':'PNG to JPG Converter Online','title':'PNG to JPG Converter Online - Convert PNG Images to JPEG | ImageToolBox','desc':'Convert PNG images to JPG in your browser with background color and quality controls.','lede':'Upload a PNG, pick a background for transparency, and download a JPEG copy instantly.','keyword':'convert png to jpg online','tag':'Conversion','calc':'png-to-jpg','inputs':'<label class="full">PNG image<input id="imageFile" type="file" accept="image/png,image/*"></label><label>JPEG quality<input id="quality" type="number" min="0.1" max="1" step="0.05" value="0.9"></label><label>Background color<input id="background" type="color" value="#ffffff"></label>','formula':'transparent PNG pixels are drawn over the selected background, then encoded as JPEG','uses':['Convert transparent PNGs','Prepare smaller JPEG photos','Make upload-compatible files','Create white-background images','Convert screenshots','Download JPEG previews']},
 {'slug':'webp-converter','name':'WebP Converter','h1':'WebP Converter Online','title':'WebP Converter Online - Convert Images to WebP, JPG or PNG | ImageToolBox','desc':'Convert images to WebP, JPG, or PNG locally with a free browser-based image format converter.','lede':'Choose an image and export it as WebP, JPEG, or PNG using canvas conversion in your browser.','keyword':'webp converter online','tag':'Conversion','calc':'webp-converter','inputs':'<label class="full">Image file<input id="imageFile" type="file" accept="image/*"></label><label>Output format<select id="format"><option value="image/webp">WebP</option><option value="image/jpeg">JPEG</option><option value="image/png">PNG</option></select></label><label>Quality<input id="quality" type="number" min="0.1" max="1" step="0.05" value="0.85"></label>','formula':'image pixels are redrawn to canvas and exported with canvas.toBlob(format, quality)','uses':['Create WebP images','Convert WebP to JPG','Export PNG copies','Test browser formats','Prepare web assets','Compare output sizes']},
]
PAGES=[('about','About ImageToolBox','Learn about ImageToolBox, a free collection of browser-based image compression, resize, and format conversion tools.'),('contact','Contact ImageToolBox','Contact ImageToolBox for feedback about free online image tools on FreeToolsSpace.'),('privacy-policy','Privacy Policy','Read the ImageToolBox privacy policy for static browser-based tools that do not require accounts or uploads.'),('cookie-policy','Cookie Policy','Read the ImageToolBox cookie policy for this static image tool collection.'),('terms-of-use','Terms of Use','Read the ImageToolBox terms of use for free educational browser image utilities.'),('disclaimer','Disclaimer','Read the ImageToolBox disclaimer for browser-based image utilities and generated outputs.')]
def esc(s): return html.escape(str(s), quote=True)
def head(title,desc,canonical,extra=''):
    return f'<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{esc(title)}</title><meta name="description" content="{esc(desc)}"><link rel="canonical" href="{canonical}"><meta property="og:type" content="website"><meta property="og:site_name" content="FreeToolsSpace"><meta property="og:title" content="{esc(title)}"><meta property="og:description" content="{esc(desc)}"><meta property="og:url" content="{canonical}"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{esc(title)}"><meta name="twitter:description" content="{esc(desc)}"><link rel="stylesheet" href="/imagetoolbox/assets/css/styles.css"><style>{THEME}</style>{extra}</head>'
def header():
    return '<header class="site-header"><nav class="navbar" aria-label="Main navigation"><a class="logo" href="/imagetoolbox/"><span class="logo-mark">I</span><span>ImageToolBox</span></a><div class="nav-links"><a href="/imagetoolbox/tools/">Tools</a><a href="/imagetoolbox/about/">About</a><a href="/imagetoolbox/contact/">Contact</a><a href="/imagetoolbox/privacy-policy/">Privacy</a></div></nav></header>'
def footer():
    links=''.join(f'<a href="/imagetoolbox/{t["slug"]}/">{esc(t["name"])}</a>' for t in TOOLS)
    return f'<footer class="site-footer"><div class="container footer-grid"><div><a class="logo" href="/imagetoolbox/"><span class="logo-mark">I</span><span>ImageToolBox</span></a><p>Free browser-based image tools for compression, resizing, and format conversion.</p><p class="small">ImageToolBox provides educational utilities. Review generated output before production use.</p></div><div><h3>Popular tools</h3>{links}</div><div><h3>Site pages</h3><a href="/imagetoolbox/tools/">All tools</a><a href="/imagetoolbox/about/">About</a><a href="/imagetoolbox/contact/">Contact</a><a href="/imagetoolbox/privacy-policy/">Privacy Policy</a><a href="/imagetoolbox/cookie-policy/">Cookie Policy</a><a href="/imagetoolbox/terms-of-use/">Terms of Use</a><a href="/imagetoolbox/disclaimer/">Disclaimer</a></div><div><h3>About this site</h3><p>Static image utilities. No account, database, or server upload is required.</p><p>Contact: hello@freetoolsspace.com</p></div></div></footer><script src="/imagetoolbox/assets/js/runtime.js" defer></script><script src="/imagetoolbox/assets/js/site-tools.js" defer></script>'
def cards():
    return ''.join(f'<a class="card" href="/imagetoolbox/{t["slug"]}/"><span class="tag">{esc(t["tag"])}</span><h3>{esc(t["name"])}</h3><p>{esc(t["desc"])}</p></a>' for t in TOOLS)
SITE.mkdir(); (SITE/'assets/css').mkdir(parents=True); (SITE/'assets/js').mkdir(parents=True)
css=(ROOT/'texttools/assets/css/styles.css').read_text()
css += '\n.preview-img{max-width:100%;height:auto;border-radius:16px;border:1px solid var(--line);margin-top:12px}.download-link{display:inline-flex;padding:12px 14px;border-radius:14px;background:var(--primary);color:white;text-decoration:none;font-weight:800}.canvas-note{font-size:.9rem;color:var(--muted)}\n'
(SITE/'assets/css/styles.css').write_text(css, encoding='utf-8')
(SITE/'assets/js/runtime.js').write_text((ROOT/'texttools/assets/js/runtime.js').read_text(), encoding='utf-8')
js=r'''(() => {
  const rt = ToolRuntime;
  function fileInput(){ const file = rt.$('#imageFile')?.files?.[0]; if(!file) throw new Error('Choose an image file first.'); return file; }
  function readImage(file){ return new Promise((resolve,reject)=>{ const url=URL.createObjectURL(file); const img=new Image(); img.onload=()=>resolve({img,url}); img.onerror=()=>reject(new Error('Could not read image file.')); img.src=url; }); }
  function blobFromCanvas(canvas, format, quality){ return new Promise(resolve => canvas.toBlob(resolve, format, quality)); }
  function drawContain(ctx,img,w,h,bg){ ctx.fillStyle=bg||'#ffffff'; ctx.fillRect(0,0,w,h); const scale=Math.min(w/img.naturalWidth,h/img.naturalHeight); const dw=Math.round(img.naturalWidth*scale), dh=Math.round(img.naturalHeight*scale); ctx.drawImage(img, Math.round((w-dw)/2), Math.round((h-dh)/2), dw, dh); }
  async function render(opts){
    const file=fileInput(); const {img,url}=await readImage(file); let w=opts.width||img.naturalWidth, h=opts.height||img.naturalHeight;
    const canvas=document.createElement('canvas'); canvas.width=w; canvas.height=h; const ctx=canvas.getContext('2d');
    if(opts.mode==='contain') drawContain(ctx,img,w,h,opts.background); else { if(opts.background){ctx.fillStyle=opts.background; ctx.fillRect(0,0,w,h);} ctx.drawImage(img,0,0,w,h); }
    URL.revokeObjectURL(url); const format=opts.format||'image/jpeg'; const blob=await blobFromCanvas(canvas,format,opts.quality||0.85); if(!blob) throw new Error('Your browser could not export this format. Try JPEG or PNG.');
    const outUrl=URL.createObjectURL(blob); const ext=format.includes('webp')?'webp':format.includes('png')?'png':'jpg'; const name=(file.name.replace(/\.[^.]+$/,'')||'image')+'-imagetoolbox.'+ext; const saved=file.size-blob.size; const pct=file.size?((saved/file.size)*100).toFixed(1):'0.0';
    rt.setResult(`<div class="output-item"><h3>Image ready</h3><div class="kv"><strong>Original</strong><span>${(file.size/1024).toFixed(1)} KB</span><strong>Output</strong><span>${(blob.size/1024).toFixed(1)} KB</span><strong>Change</strong><span>${pct}% smaller</span><strong>Dimensions</strong><span>${w} × ${h}px</span></div><p><a class="download-link" href="${outUrl}" download="${rt.escapeHtml(name)}">Download image</a></p><img class="preview-img" alt="Converted image preview" src="${outUrl}"><p class="canvas-note">Processing happened locally in this browser tab.</p></div>`,'success');
  }
  const handlers={
    'image-compressor':async()=>{ const file=fileInput(); const {img,url}=await readImage(file); const max=Number(rt.value('maxWidth'))||img.naturalWidth; const scale=Math.min(1,max/img.naturalWidth); URL.revokeObjectURL(url); await render({width:Math.round(img.naturalWidth*scale),height:Math.round(img.naturalHeight*scale),format:rt.value('format')||'image/jpeg',quality:Number(rt.value('quality'))||0.8,background:'#ffffff'}); },
    'image-resizer':async()=>render({width:Math.max(1,Number(rt.value('width'))||1200),height:Math.max(1,Number(rt.value('height'))||800),mode:rt.value('mode'),format:rt.value('format')||'image/jpeg',quality:.9,background:'#ffffff'}),
    'png-to-jpg':async()=>{ const file=fileInput(); const {img,url}=await readImage(file); URL.revokeObjectURL(url); await render({width:img.naturalWidth,height:img.naturalHeight,format:'image/jpeg',quality:Number(rt.value('quality'))||.9,background:rt.value('background')||'#ffffff'}); },
    'webp-converter':async()=>{ const file=fileInput(); const {img,url}=await readImage(file); URL.revokeObjectURL(url); await render({width:img.naturalWidth,height:img.naturalHeight,format:rt.value('format')||'image/webp',quality:Number(rt.value('quality'))||.85,background:'#ffffff'}); }
  };
  document.addEventListener('click', async (event)=>{ const b=event.target.closest('[data-calculate]'); if(!b) return; try{ rt.setResult('<p class="small">Processing image...</p>'); await handlers[b.dataset.calculate]?.(); }catch(e){ rt.error(e.message); } });
})();
'''
(SITE/'assets/js/site-tools.js').write_text(js, encoding='utf-8')
extra='<script type="application/ld+json">'+json.dumps({'@context':'https://schema.org','@type':'CollectionPage','name':'ImageToolBox','url':BASE,'description':'Free online image compression, resize, and conversion tools.'},separators=(',',':'))+'</script>'
index=f'<!doctype html><html lang="en">{head("ImageToolBox | Free Online Image Compressor, Resizer and Converter","Use ImageToolBox on FreeToolsSpace for free browser-based image compression, resizing, PNG to JPG conversion, and WebP conversion tools.",BASE,extra)}<body>{header()}<main><section class="hero"><div class="container hero-grid"><div><p class="eyebrow">Image tools</p><h1>Free Online Image Tools</h1><p class="lede">Compress, resize, and convert images with static browser utilities that keep files on your device.</p><div class="cta-row"><a class="button" href="/imagetoolbox/tools/">Browse Tools</a><a class="button secondary" href="/imagetoolbox/about/">About ImageToolBox</a></div></div><div class="hero-card"><h2>Local image processing</h2><ul><li>No account, upload, or backend required</li><li>Works with common JPG, PNG, and WebP files</li><li>Download-ready output from every tool</li><li>FAQ, examples, and related links included</li></ul></div></div></section><section class="section"><div class="container"><h2>Popular Image Tools</h2><p class="lede">Start with compression, resizing, and format conversion utilities.</p><div class="grid">{cards()}</div></div></section><section class="section"><div class="container"><h2>Choose the right image utility</h2><p class="lede">ImageToolBox focuses on safe frontend-only tools for everyday web image workflows.</p><div class="grid"><div class="card"><span class="tag">Compress</span><h3>Reduce image size</h3><p>Use the image compressor to lower file size before uploading or publishing.</p></div><div class="card"><span class="tag">Resize</span><h3>Change dimensions</h3><p>Use the image resizer for thumbnails, previews, profile images, and article graphics.</p></div><div class="card"><span class="tag">Convert</span><h3>Switch formats</h3><p>Convert PNG, JPG, and WebP outputs when a website or workflow needs a different format.</p></div></div></div></section></main>{footer()}</body></html>'
(SITE/'index.html').write_text(index, encoding='utf-8'); (SITE/'404.html').write_text(index.replace('<h1>Free Online Image Tools</h1>','<h1>Page Not Found</h1>'), encoding='utf-8')
(SITE/'tools').mkdir(); (SITE/'tools/index.html').write_text(f'<!doctype html><html lang="en">{head("ImageToolBox Tools Index | Free Online Image Utilities","Browse the full ImageToolBox index for image compression, resizing, PNG to JPG conversion, and WebP conversion.",BASE+"tools/")}<body>{header()}<main class="page-main"><div class="container"><div class="breadcrumb"><a href="/imagetoolbox/">Home</a> / Tools</div><h1>Free Online Image Tools</h1><p class="lede">Browse free image compressor, image resizer, PNG to JPG converter, and WebP converter tools.</p><div class="grid">{cards()}</div></div></main>{footer()}</body></html>', encoding='utf-8')
for t in TOOLS:
    (SITE/t['slug']).mkdir(); url=BASE+t['slug']+'/'
    faq={'@context':'https://schema.org','@type':'FAQPage','mainEntity':[{'@type':'Question','name':f'What does the {t["name"]} do?','acceptedAnswer':{'@type':'Answer','text':t['desc']}},{'@type':'Question','name':'Is my image uploaded?','acceptedAnswer':{'@type':'Answer','text':'No. The tool runs locally in your browser on this static site.'}},{'@type':'Question','name':'Can I use it on mobile?','acceptedAnswer':{'@type':'Answer','text':'Yes. The page is responsive and works on mobile browsers that support canvas image export.'}},{'@type':'Question','name':'Can I download the result?','acceptedAnswer':{'@type':'Answer','text':'Yes. After processing, use the Download image link.'}},{'@type':'Question','name':'Should I keep the original file?','acceptedAnswer':{'@type':'Answer','text':'Yes. Keep the original image if quality or metadata is important.'}}]}
    extra=''.join('<script type="application/ld+json">'+json.dumps(x,separators=(',',':'))+'</script>' for x in ({'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Home','item':BASE},{'@type':'ListItem','position':2,'name':'Tools','item':BASE+'tools/'},{'@type':'ListItem','position':3,'name':t['name'],'item':url}]},{'@context':'https://schema.org','@type':'SoftwareApplication','name':t['name'],'applicationCategory':'MultimediaApplication','operatingSystem':'Any','url':url,'offers':{'@type':'Offer','price':'0','priceCurrency':'USD'}},faq))
    related=''.join(f'<a href="/imagetoolbox/{o["slug"]}/">{esc(o["name"])}</a>' for o in TOOLS if o['slug']!=t['slug'])+'<a href="/imagetoolbox/tools/">All ImageToolBox Tools</a>'
    uses=''.join(f'<li>{esc(u)}</li>' for u in t['uses'])
    doc=f'<!doctype html><html lang="en">{head(t["title"],t["desc"],url,extra)}<body>{header()}<main class="page-main"><div class="container"><div class="breadcrumb"><a href="/imagetoolbox/">Home</a> / <a href="/imagetoolbox/tools/">Tools</a> / {esc(t["name"])}</div><p class="eyebrow">{esc(t["tag"])}</p><h1>{esc(t["h1"])}</h1><p class="lede">{esc(t["lede"])}</p><div class="ad-slot" data-ad-position="top">Advertisement</div><div class="tool-layout"><section class="tool-card" data-tool="{esc(t["calc"])}"><h2>Free {esc(t["name"])}</h2><p class="small">This tool runs in your browser and does not upload your image. Results include a download link after processing.</p><div class="form-grid">{t["inputs"]}</div><div class="actions"><button data-calculate="{esc(t["calc"])}">Process Image</button><button class="secondary" data-reset-tool>Reset</button></div></section><aside class="result-card"><h2>Results</h2><div id="result" class="output"><p class="small">Choose an image and process it to see results here.</p></div><div class="ad-slot sidebar" data-ad-position="sidebar">Advertisement</div></aside></div><article class="content"><section><h2>What this tool does</h2><p>The {esc(t["name"])} helps with {esc(t["keyword"])} tasks while keeping files in your own browser.</p></section><section><h2>Formula or rule</h2><div class="formula-box"><code>{esc(t["formula"])}</code></div></section><section><h2>Common use cases</h2><ul class="use-case-grid">{uses}</ul></section><section><h2>Related tools</h2><div class="related">{related}</div></section><section><h2>Disclaimer</h2><p>ImageToolBox provides educational browser-based image utilities. Keep original files when quality, color accuracy, or metadata matters.</p></section><section class="faq"><h2>FAQ</h2><details><summary>What does the {esc(t["name"])} do?</summary><p>{esc(t["desc"])}</p></details><details><summary>Is my image uploaded?</summary><p>No. The tool runs locally in your browser on this static site.</p></details><details><summary>Can I use it on mobile?</summary><p>Yes, on mobile browsers that support canvas image export.</p></details><details><summary>Can I download the result?</summary><p>Yes. After processing, use the Download image link.</p></details><details><summary>Should I keep the original file?</summary><p>Yes. Keep the original image if quality or metadata is important.</p></details></section></article></div></main>{footer()}</body></html>'
    (SITE/t['slug']/'index.html').write_text(doc, encoding='utf-8')
for slug,title,desc in PAGES:
    (SITE/slug).mkdir(); body=f'<!doctype html><html lang="en">{head(title+" | ImageToolBox",desc,BASE+slug+"/")}<body>{header()}<main class="page-main"><div class="container"><div class="breadcrumb"><a href="/imagetoolbox/">Home</a> / {esc(title)}</div><h1>{esc(title)}</h1><p class="lede">{esc(desc)}</p><article class="content"><p>ImageToolBox is part of FreeToolsSpace and offers static browser utilities for common image tasks. The tools are designed for quick educational and productivity use without accounts, uploads, databases, or backend processing.</p><p>For important production work, keep original files and review generated images before using them in live systems.</p><h2>Popular tools</h2><div class="related">{"".join(f"<a href=/imagetoolbox/{t["slug"]}/>{esc(t["name"])}</a>" for t in TOOLS)}</div></article></div></main>{footer()}</body></html>'
    (SITE/slug/'index.html').write_text(body, encoding='utf-8')
# root homepage updates
root_index=ROOT/'index.html'; text=root_index.read_text()
if '/imagetoolbox/' in text: raise SystemExit('Collision: homepage already references /imagetoolbox/.')
text=text.replace('Seven independent browser tool sites','Eight independent browser tool sites')
text=text.replace('dates, unit conversions, math, wages, money, health, lifestyle planning, text editing, and developer utilities','dates, unit conversions, math, wages, money, health, lifestyle planning, text editing, developer utilities, and image tools')
text=text.replace('<a href="/devtoolbox/">DevToolBox</a></div>','<a href="/devtoolbox/">DevToolBox</a><a href="/imagetoolbox/">ImageToolBox</a></div>')
text=text.replace('</ul>\n        <a class="open-link" href="/devtoolbox/" aria-label="Open DevToolBox">Open DevToolBox →</a>\n      </article>\n      </div>','</ul>\n        <a class="open-link" href="/devtoolbox/" aria-label="Open DevToolBox">Open DevToolBox →</a>\n      </article>\n      <article class="tool-card" style="--accent:#db2777">\n        <div class="card-index">08</div>\n        <p class="card-kicker">Image Tools</p>\n        <h2><a href="/imagetoolbox/">ImageToolBox</a></h2>\n        <p>Image compression, resizing, PNG to JPG conversion, and WebP conversion in your browser.</p>\n        <ul><li>Image Compressor</li><li>Image Resizer</li><li>WebP Converter</li></ul>\n        <a class="open-link" href="/imagetoolbox/" aria-label="Open ImageToolBox">Open ImageToolBox →</a>\n      </article>\n      </div>')
text=text.replace('<li><a href="/devtoolbox/">DevToolBox - JSON formatter, Base64 encoder decoder, URL encoder decoder, and UUID generator</a></li></ul>','<li><a href="/devtoolbox/">DevToolBox - JSON formatter, Base64 encoder decoder, URL encoder decoder, and UUID generator</a></li><li><a href="/imagetoolbox/">ImageToolBox - image compressor, image resizer, PNG to JPG converter, and WebP converter</a></li></ul>')
text=text.replace('including the new DevToolBox developer utilities.','including the new DevToolBox developer utilities and ImageToolBox image utilities.')
text=text.replace('{"@type":"ListItem","position":7,"name":"DevToolBox","url":"https://freetoolsspace.com/devtoolbox/"}','{"@type":"ListItem","position":7,"name":"DevToolBox","url":"https://freetoolsspace.com/devtoolbox/"},{"@type":"ListItem","position":8,"name":"ImageToolBox","url":"https://freetoolsspace.com/imagetoolbox/"}')
root_index.write_text(text, encoding='utf-8')
# sitemap
sitemap=ROOT/'sitemap.xml'; sm=sitemap.read_text()
if 'https://freetoolsspace.com/imagetoolbox/' in sm: raise SystemExit('Collision: sitemap already references imagetoolbox.')
urls=['imagetoolbox/','imagetoolbox/tools/']+[f'imagetoolbox/{t["slug"]}/' for t in TOOLS]+[f'imagetoolbox/{slug}/' for slug,_,_ in PAGES]
entries=''.join(f'  <url>\n    <loc>https://freetoolsspace.com/{u}</loc>\n    <lastmod>{TODAY}</lastmod>\n    <changefreq>{"weekly" if u in ["imagetoolbox/","imagetoolbox/tools/"] else "monthly"}</changefreq>\n    <priority>{"0.8" if u == "imagetoolbox/" else "0.7"}</priority>\n  </url>\n' for u in urls)
sm=sm.replace('</urlset>',entries+'</urlset>'); sitemap.write_text(sm, encoding='utf-8')
print('Created ImageToolBox with',len(TOOLS),'tools at',SITE); print('Updated root index and sitemap entries:',len(urls))
